# -*- coding: utf-8 -*-
# vim: ft=yaml
---
###############################################################################
# Define all YAML node anchors
###############################################################################
.node_anchors:
  # `only` (also used for `except` where applicable)
  only_branch_master_parent_repo: &only_branch_master_parent_repo
    - 'master@saltstack-formulas/zabbix-formula'
  # `stage`
  stage_lint: &stage_lint 'lint'
  stage_release: &stage_release 'release'
  stage_test: &stage_test 'test'
  # `image`
  image_coala: &image_coala 'thomasboni/coala:latest'
  image_commitlint: &image_commitlint 'myii/ssf-commitlint:11'
  image_dindruby: &image_dindruby 'myii/ssf-dind-ruby:2.7.1-r3'
  image_precommit: &image_precommit
    name: 'myii/ssf-pre-commit:2.9.2'
    entrypoint: ['/bin/bash', '-c']
  image_rubocop: &image_rubocop 'pipelinecomponents/rubocop:latest'
  image_semantic-release: &image_semanticrelease 'myii/ssf-semantic-release:15.14'
  # `services`
  services_docker_dind: &services_docker_dind
    - 'docker:dind'
  # `variables`
  # https://forum.gitlab.com/t/gitlab-com-ci-caching-rubygems/5627/3
  # https://bundler.io/v1.16/bundle_config.html
  variables_bundler: &variables_bundler
    BUNDLE_CACHE_PATH: '${CI_PROJECT_DIR}/.cache/bundler'
    BUNDLE_WITHOUT: 'production'
  # `cache`
  cache_bundler: &cache_bundler
    key: '${CI_JOB_STAGE}'
    paths:
      - '${BUNDLE_CACHE_PATH}'

###############################################################################
# Define stages and global variables
###############################################################################
stages:
  - *stage_lint
  - *stage_test
  - *stage_release
variables:
  DOCKER_DRIVER: 'overlay2'

###############################################################################
# `lint` stage: `commitlint`, `pre-commit`, `rubocop` (latest, failure allowed)
#               & `coala` (dev, failure allowed)
###############################################################################
coala:
  # allow_failure: true
  stage: *stage_lint
  image: *image_coala
  script:
    - 'coala --ci --files docs/README.rst --bears reSTLintBear
             --min-severity NORMAL --no-autoapply-warn'

###############################################################################
# Define `test` template
###############################################################################
.test_instance:
  stage: *stage_test
  image: *image_dindruby
  services: *services_docker_dind
  variables: *variables_bundler
  cache: *cache_bundler
  before_script:
    # TODO: This should work from the env vars above automatically
    - 'bundle config set path "${BUNDLE_CACHE_PATH}"'
    - 'bundle config set without "${BUNDLE_WITHOUT}"'
    - 'bundle install'
  script:
    # Alternative value to consider: `${CI_JOB_NAME}`
    - 'bin/kitchen verify "${DOCKER_ENV_CI_JOB_NAME}"'

###############################################################################
# `test` stage: each instance below uses the `test` template above
###############################################################################
## Define the rest of the matrix based on Kitchen testing
# Make sure the instances listed below match up with
# the `platforms` defined in `kitchen.yml`

###############################################################################
# `release` stage: `semantic-release`
###############################################################################
semantic-release:
  only: *only_branch_master_parent_repo
  stage: *stage_release
  image: *image_semanticrelease
  variables:
    MAINTAINER_TOKEN: '${GH_TOKEN}'
  script:
    # Update `AUTHORS.md`
    - '${HOME}/go/bin/maintainer contributor'
    # Run `semantic-release`
    - 'semantic-release'
