= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v1.0.5...v1.1.0++[1.1.0^] (2021-04-16)

=== Features

* add suse support (applied suggestions from hatifnatt and myii)
(https://github.com/saltstack-formulas/zabbix-formula/commit/a245ec44954b3e782787fb09cd84655597cfac01[a245ec4^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v1.0.4...v1.0.5++[1.0.5^] (2021-04-16)

=== Bug Fixes

* *agent:* fix include dirname
(https://github.com/saltstack-formulas/zabbix-formula/commit/b36c1a7541c7cbe27fc108a3fd82d78d9cd1f758[b36c1a7^])

=== Continuous Integration

* *commitlint:* ensure `upstream/master` uses main repo URL [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/f562f9f3e4f757d10ac024cba7fa67649ddda799[f562f9f^])
* *gemfile+lock:* use `ssf` customised `kitchen-docker` repo [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/1fed2667ba186102036d0efb74394ccd54a759ec[1fed266^])
* *gitlab-ci:* add `rubocop` linter (with `allow_failure`) [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/479929200b96994c1dcd20e844c201489646ebb2[4799292^])
* *kitchen+ci:* use latest pre-salted images (after CVE) [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/aaf82ded69295e62dd871e5be600b1aa1a2d05e5[aaf82de^])
* *kitchen+gitlab-ci:* use latest pre-salted images [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/1701026b0dd547af8a1b0c765865910d0fd2616c[1701026^])
* *pre-commit:* update hook for `rubocop` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/751e966a788ed7716219a20bf549d07b2bdf3ad0[751e966^])

=== Tests

* standardise use of `share` suite & `_mapdata` state [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/05eae71461c0ee2f3c99108c884de9f64d09a896[05eae71^])
* *config_spec:* fix `rubocop` violations [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/fb270d2ffbde0386121a87523adf3ca1bbf85cee[fb270d2^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v1.0.3...v1.0.4++[1.0.4^] (2020-12-16)

=== Continuous Integration

* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/zabbix-formula/commit/44ec1b3d71de71efab27a2f2ccb58c90018cedbe[44ec1b3^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/c9aeb377d070cae54aa82f15904ab799b5994980[c9aeb37^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/8990e81dc256d53249bf2732e5b8af1346133e76[8990e81^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/c7dff99d06e25572fc9ee74ec1655fdd8e41cd8a[c7dff99^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/497406a77a3431d2e708e2eeadca9221a1833ebf[497406a^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v1.0.2...v1.0.3++[1.0.3^] (2020-07-10)

=== Code Refactoring

* *variable names:* use dbpassword consistently across formula
(https://github.com/saltstack-formulas/zabbix-formula/commit/5b4b78795ef4396b4a94b68af9e04c374b631194[5b4b787^])

=== Continuous Integration

* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/aa92ed55e14526a8882a36b151216a2da408ad51[aa92ed5^])

=== Tests

* *packages_spec:* generalise version number verification [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/e4952f06f3e2c131a2beb2e30b56f6c3e7b4581a[e4952f0^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v1.0.1...v1.0.2++[1.0.2^] (2020-05-28)

=== Continuous Integration

* *kitchen+travis:* add new platforms [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/e7ff4eeb77198628d75cd3f2b01b6f8f6ce55438[e7ff4ee^])
* *kitchen+travis:* adjust matrix to add `3000.3` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/02926f08e1220baa5c92c0b5f1ef130195b3b50e[02926f0^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/473db1cc7689d3f1ed42d02873f4208f5cf4fea9[473db1c^])
* *travis:* use new platforms (`ubuntu-20.04` & `fedora-32`)
(https://github.com/saltstack-formulas/zabbix-formula/commit/938aac4f93472350bcd0fdfc387938494e898541[938aac4^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/ac271fe041199e71c0186fc83916c325ad22c91b[ac271fe^])

=== Tests

* *packages_spec:* add versions for new platforms
(https://github.com/saltstack-formulas/zabbix-formula/commit/5eb7bd8d6a74bc0f49ab7703f205ac59ccf49bf8[5eb7bd8^])
* *packages_spec:* update for `4.4.9`
(https://github.com/saltstack-formulas/zabbix-formula/commit/d30ae38e1ec551be3bd456f64091e95692cf30ac[d30ae38^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v1.0.0...v1.0.1++[1.0.1^] (2020-05-02)

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/6f153fa8c3609470cbaa93a38f886c089866a74d[6f153fa^])
* *kitchen+travis:* adjust matrix to add `3000.2` & remove `2018.3`
(https://github.com/saltstack-formulas/zabbix-formula/commit/fc6c741fbbc50f4569e2218ef62b2a79e710c5c2[fc6c741^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/92ac6c762061bb45e1f02bc6b40a5887355f3462[92ac6c7^])

=== Tests

* *packages_spec:* update for `4.4.8`
(https://github.com/saltstack-formulas/zabbix-formula/commit/773e522a26dbf391c844182c26a1bef058b9e4b9[773e522^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v0.21.4...v1.0.0++[1.0.0^] (2020-04-04)

=== Bug Fixes

* *fedora:* get all `fedora` instances working (`2018.3`+)
(https://github.com/saltstack-formulas/zabbix-formula/commit/32ef0e61fa25d45dbd9ad3f62eaf5166b96d1298[32ef0e6^])

=== Continuous Integration

* *kitchen+travis:* adjust matrix to add `3000` & remove `2017.7` [skip
ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/74bb0322724aa5adb728f194372ff10464d433bd[74bb032^])
* *kitchen+travis:* adjust matrix to update `3000` to `3000.1` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/e74bfed5e97ec03037b9dc560a113597f2a295d2[e74bfed^])

=== BREAKING CHANGES

* *fedora:* Minimum Salt version support is now `2018.3` in line with
official upstream support; also use of the `traverse` Jinja filter.

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v0.21.3...v0.21.4++[0.21.4^] (2020-03-31)

=== Tests

* *packages_spec:* update version numbers
(https://github.com/saltstack-formulas/zabbix-formula/commit/3242c1469662ffc14368446df5eb11a140ebd2ea[3242c14^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v0.21.2...v0.21.3++[0.21.3^] (2020-03-22)

=== Code Refactoring

* *map and defaults:* update the map.jinja file and add yaml maps
(https://github.com/saltstack-formulas/zabbix-formula/commit/badd17edecff8119fe25d73329c0445a3ac58769[badd17e^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v0.21.1...v0.21.2++[0.21.2^] (2020-03-12)

=== Bug Fixes

* *libtofs:* “files_switch” mess up the variable exported by “map.jinja”
 [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/9d6b5d7af2fdce59c104d4580d17880f4a5bf8d3[9d6b5d7^])
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/2072e06d91fdc74781bf88c33f90ec408b241abd[2072e06^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/95d4c151327987fc287dc682868a7e962e898dfb[95d4c15^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/2c04d9311de15b56613a51b95b12bde536ea413e[2c04d93^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/8645a8ee6ea8e1b77c62801929d175cf3d683169[8645a8e^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/678b048c34a8483f6bca79796a4e39f07760e5e4[678b048^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/495f811341907cccf831970cc9da9fff3999f456[495f811^])
* *travis:* adjust to new working matrix
(https://github.com/saltstack-formulas/zabbix-formula/commit/41cd6abb624617b8d78b572d0e75ecf42a1f9787[41cd6ab^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/082461270d6286709d2405aaa310f51431290df9[0824612^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/6e8da049ea0089bb0fd60f74c3e1c9956cf8ff54[6e8da04^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/0c33ab0eb88beebb422e76effa2262bba4310a6b[0c33ab0^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/33b018d8013cf5e895c2ba20c0a82c04e5cfb1c7[33b018d^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/ecc08c40c2c21ca7ffa197fd376ab61a92d3d4a3[ecc08c4^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/ece1158ec2138fd111684e3af9606df8b5d0776d[ece1158^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/f4f8626d822539deb2f353612f3cfa725530b163[f4f8626^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/889a49bab69e51efb70be6185adf2f57553c71c0[889a49b^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/249b89fb4af4cdbaa29220fd8eee8520a42f67ed[249b89f^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/zabbix-formula/commit/a5b7afb8842bf5744080bef8d49464e914923f2b[a5b7afb^])

=== Tests

* *packages_spec:* update for `4.4.1` release
(https://github.com/saltstack-formulas/zabbix-formula/commit/c5cc431f9489da2139c7ca14ff28797ce859262b[c5cc431^])
* *packages_spec:* update version numbers
(https://github.com/saltstack-formulas/zabbix-formula/commit/0ebd417860f157b3d6a31c2b1522db380ece6673[0ebd417^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v0.21.0...v0.21.1++[0.21.1^] (2019-10-13)

=== Code Refactoring

* *repo:* remove unused `files_switch` import
(https://github.com/saltstack-formulas/zabbix-formula/commit/e60e111[e60e111^])
* *tofs:* upgrade for all file.managed
(https://github.com/saltstack-formulas/zabbix-formula/commit/d5c747c[d5c747c^])

=== Continuous Integration

* *travis:* use `fedora-29` instead of `fedora-30` (for reliability)
(https://github.com/saltstack-formulas/zabbix-formula/commit/7de7782[7de7782^])

== link:++https://github.com/saltstack-formulas/zabbix-formula/compare/v0.20.5...v0.21.0++[0.21.0^] (2019-10-12)

=== Bug Fixes

* *init.sls:* fix `salt-lint` errors
(https://github.com/saltstack-formulas/zabbix-formula/commit/ff28364[ff28364^])
* *pillar.example:* fix `yamllint` violations
(https://github.com/saltstack-formulas/zabbix-formula/commit/b51907d[b51907d^])
* *repo:* ensure `debconf-utils` is installed for Debian-based OSes
(https://github.com/saltstack-formulas/zabbix-formula/commit/4980350[4980350^])

=== Continuous Integration

* *inspec:* add pillar to use for testing the `default` suite
(https://github.com/saltstack-formulas/zabbix-formula/commit/581a748[581a748^])

=== Documentation

* *readme:* move to `docs/` directory and apply common structure
(https://github.com/saltstack-formulas/zabbix-formula/commit/f0f1563[f0f1563^])

=== Features

* *semantic-release:* implement for this formula
(https://github.com/saltstack-formulas/zabbix-formula/commit/40e78a2),
closes
https://github.com/saltstack-formulas/zabbix-formula/issues/129[#129^]

=== Tests

* *inspec:* add tests for packages, config files & services
(https://github.com/saltstack-formulas/zabbix-formula/commit/4facac6[4facac6^])
